import 'package:sqflite/sqflite.dart';

import 'package:baqati/data/app_database.dart';
import 'package:baqati/models/event_type.dart';
import 'package:baqati/models/package_event.dart';

/// Queries over the `events` table, replacing the Kotlin's Room DAO.
class PackageEventDao {
  const PackageEventDao(this._db);

  final AppDatabase _db;

  /// PORT-FIX: the Kotlin's "latest" queries ordered by `timestamp DESC` alone.
  /// A single parsed SMS can emit several events that all share one `now`
  /// timestamp, so which row surfaced as "latest" was left to SQLite and could
  /// change between runs. The row id breaks the tie deterministically.
  static const String _newestFirst = 'timestamp DESC, id DESC';

  Future<List<PackageEvent>> getAllEvents() async {
    final Database db = await _db.database;
    final List<Map<String, Object?>> rows = await db.query(
      PackageEvent.tableName,
      orderBy: _newestFirst,
    );
    return rows.map(PackageEvent.fromMap).toList();
  }

  Future<PackageEvent?> getLatestEvent() async {
    final Database db = await _db.database;
    final List<Map<String, Object?>> rows = await db.query(
      PackageEvent.tableName,
      orderBy: _newestFirst,
      limit: 1,
    );
    return rows.isEmpty ? null : PackageEvent.fromMap(rows.first);
  }

  Future<PackageEvent?> getLatestEventByType(EventType type) async {
    final Database db = await _db.database;
    final List<Map<String, Object?>> rows = await db.query(
      PackageEvent.tableName,
      where: 'type = ?',
      whereArgs: <Object?>[type.wireName],
      orderBy: _newestFirst,
      limit: 1,
    );
    return rows.isEmpty ? null : PackageEvent.fromMap(rows.first);
  }

  /// Packages that have not yet expired, soonest expiry first.
  Future<List<PackageEvent>> getActivePackages(int nowMillis) async {
    final Database db = await _db.database;
    final List<Map<String, Object?>> rows = await db.query(
      PackageEvent.tableName,
      where: 'expiry_timestamp > ?',
      whereArgs: <Object?>[nowMillis],
      orderBy: 'expiry_timestamp ASC',
    );
    return rows.map(PackageEvent.fromMap).toList();
  }

  /// Inserts [event], returning its new row id — or 0 when it was ignored as a
  /// duplicate of an already-imported message.
  Future<int> insert(PackageEvent event) async {
    final Database db = await _db.database;
    return db.insert(
      PackageEvent.tableName,
      event.toMap(),
      // PORT-FIX: the Kotlin used Room's REPLACE strategy, which never fired
      // because every event was built with an autogenerated primary key and so
      // had nothing to conflict on. Ignoring on conflict is what makes
      // re-running the inbox backfill safe.
      conflictAlgorithm: ConflictAlgorithm.ignore,
    );
  }

  /// Inserts [events] in one transaction, returning how many were ACTUALLY
  /// written.
  ///
  /// The count excludes rows ignored as duplicates, because callers report it
  /// to the user as the number of newly-found events.
  Future<int> insertAll(List<PackageEvent> events) async {
    if (events.isEmpty) return 0;

    final Database db = await _db.database;
    int inserted = 0;

    await db.transaction((Transaction txn) async {
      for (final PackageEvent event in events) {
        final int id = await txn.insert(
          PackageEvent.tableName,
          event.toMap(),
          conflictAlgorithm: ConflictAlgorithm.ignore,
        );
        if (id != 0) inserted++;
      }
    });

    return inserted;
  }

  Future<void> deleteById(int id) async {
    final Database db = await _db.database;
    await db.delete(
      PackageEvent.tableName,
      where: 'id = ?',
      whereArgs: <Object?>[id],
    );
  }

  Future<void> clearAll() async {
    final Database db = await _db.database;
    await db.delete(PackageEvent.tableName);
  }
}
