import 'package:baqati/models/event_type.dart';

/// One parsed SMS event or manually-entered reminder.
///
/// Mirrors the Kotlin `PackageEvent` Room entity, with two added columns —
/// see [balance] and [sourceHash].
///
/// [title] and [description] hold final Arabic display text rather than
/// localization keys, matching the reference. Anything reading these should
/// render them directly.
class PackageEvent {
  const PackageEvent({
    required this.type,
    required this.timestamp,
    required this.title,
    required this.description,
    this.id,
    this.minutes,
    this.sms,
    this.megabytes,
    this.expiryTimestamp,
    this.cost,
    this.balance,
    this.sourceHash,
  });

  /// Row id. Null until the row has been inserted.
  final int? id;

  final EventType type;

  /// When the event occurred, in epoch milliseconds.
  final int timestamp;

  final int? minutes;
  final int? sms;

  /// Data allowance in megabytes.
  ///
  /// Values quoted by the carrier in جيجا are converted at 1024 MB/GB before
  /// reaching this field.
  final double? megabytes;

  /// When the package expires, in epoch milliseconds.
  final int? expiryTimestamp;

  /// Money spent — a payment amount or a subscription deduction.
  ///
  /// Null for balance checks. See [balance].
  final double? cost;

  /// PORT-FIX: remaining credit, in riyal.
  ///
  /// The Kotlin stored this in `cost`, mixing an asset into a field meaning
  /// "money spent", which would silently corrupt any total-spent aggregate.
  final double? balance;

  /// PORT-FIX: SHA-256 of the originating SMS body combined with the provider's
  /// message date, used as the dedupe key.
  ///
  /// The Kotlin had no dedupe at all: every inbox sync re-inserted the same
  /// messages as new rows, because the autogenerated primary key meant Room's
  /// `OnConflictStrategy.REPLACE` never had anything to conflict on.
  ///
  /// Null for manually-entered events, which have no source message.
  final String? sourceHash;

  /// Final Arabic display text, not a localization key.
  final String title;
  final String description;

  static const String tableName = 'events';

  Map<String, Object?> toMap() => <String, Object?>{
    if (id != null) 'id': id,
    'type': type.wireName,
    'timestamp': timestamp,
    'minutes': minutes,
    'sms': sms,
    'megabytes': megabytes,
    'expiry_timestamp': expiryTimestamp,
    'cost': cost,
    'balance': balance,
    'title': title,
    'description': description,
    'source_hash': sourceHash,
  };

  factory PackageEvent.fromMap(Map<String, Object?> map) => PackageEvent(
    id: map['id'] as int?,
    type: EventType.fromWireName(map['type']! as String),
    timestamp: map['timestamp']! as int,
    minutes: map['minutes'] as int?,
    sms: map['sms'] as int?,
    megabytes: (map['megabytes'] as num?)?.toDouble(),
    expiryTimestamp: map['expiry_timestamp'] as int?,
    cost: (map['cost'] as num?)?.toDouble(),
    balance: (map['balance'] as num?)?.toDouble(),
    title: map['title']! as String,
    description: map['description']! as String,
    sourceHash: map['source_hash'] as String?,
  );

  PackageEvent copyWith({
    int? id,
    EventType? type,
    int? timestamp,
    int? minutes,
    int? sms,
    double? megabytes,
    int? expiryTimestamp,
    double? cost,
    double? balance,
    String? title,
    String? description,
    String? sourceHash,
  }) => PackageEvent(
    id: id ?? this.id,
    type: type ?? this.type,
    timestamp: timestamp ?? this.timestamp,
    minutes: minutes ?? this.minutes,
    sms: sms ?? this.sms,
    megabytes: megabytes ?? this.megabytes,
    expiryTimestamp: expiryTimestamp ?? this.expiryTimestamp,
    cost: cost ?? this.cost,
    balance: balance ?? this.balance,
    title: title ?? this.title,
    description: description ?? this.description,
    sourceHash: sourceHash ?? this.sourceHash,
  );
}
